CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS web AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS audit AUTHORIZATION CURRENT_USER;

REVOKE ALL ON SCHEMA core FROM PUBLIC;
REVOKE ALL ON SCHEMA web FROM PUBLIC;
REVOKE ALL ON SCHEMA audit FROM PUBLIC;

GRANT USAGE ON SCHEMA core TO authweave_core_runtime;
GRANT USAGE ON SCHEMA web TO authweave_web_runtime;
GRANT USAGE ON SCHEMA audit TO authweave_core_runtime, authweave_web_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA core
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authweave_core_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA core
  GRANT USAGE, SELECT ON SEQUENCES TO authweave_core_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA web
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authweave_web_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA web
  GRANT USAGE, SELECT ON SEQUENCES TO authweave_web_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA audit
  GRANT SELECT, INSERT ON TABLES TO authweave_core_runtime, authweave_web_runtime;
